adaptive_cruise_control_node:
  ros__parameters:
    laser_topic: "/scan"
    camera_topic: "/camera/image_raw/decompressed"
    camera_info_topic: "/camera/camera_info"
    detection_topic: "/detection_result"
    throttle_publisher_topic: "/throttle"
    serial_port: "/dev/ttyUSB0"
    serial_baudrate: 115200
    translation_vector: [0.1, 0.4, -0.2]
    rotation_matrix: [1.0, 0.0, 0.0,
                      0.0, 1.0, 0.0,
                      0.0, 0.0, 1.0]
    timer_value: 1000.0 # in ms
    kp_value: 100
    ki_value: 10
    kd_value: 5
    pid_max: 1500.0
    pid_min: 0.0
    adaptive_cruise_controller_flag: true
    adaptive_cruite_controller_topic: "/adaptive_cruise_controller_flag"
    